CREATE TABLE notes (
	id	INTEGER NOT NULL,
	title	TEXT NOT NULL,
	message	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);

CREATE TABLE users (
	id INTEGER NOT NULL,
	email TEXT NOT NULL,
	nickname TEXT NOT NULL,
	password TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
)